Добавил базовую разметку главной страницы
htmlacademy-htmlcss/831025-nerds-30 pull request #2
Opened 2021-01-23 18:20 UTC by JellyInLaw

2021-01-25 06:25 UTC, craz3r requested changes
Хорошо бы поправить форматирование кода, в некоторых местах его довольно трудно читать

2021-01-25 06:25 UTC, craz3r commented on index.html
> +          <li>Barbershop Borodinski</li>
Остальные элементы этого списка тоже нужно обернуть в ссылки, пусть и с пустыми адресами

2021-01-25 06:25 UTC, craz3r commented on index.html
> +        <button>Напишите нам</button>
Лучше переделать на ссылку, тк если js не будет работать на сайте то кнопка тоже не сработает, а ссылка может перенаправить на страницу с обратной связью

2021-01-25 06:25 UTC, craz3r commented on catalog.html
> +        <form action="https://echo.htmlacademy.ru" method="get">
Фильтры сбоку должны быть в форме, верхний же фильтр это скорее просто несколько ссылок, к тому же кнопка сабмита формы отсутствует, непонятно как ее отправить, в этом кейсе фильтры применяются сразу после клика на какой либо из них, что тоже говорит о том что лучше использовать здесь ссылки

2021-01-25 06:25 UTC, craz3r commented on catalog.html
> +              <p>Продуктовый лендинг<br />приложения для iOS и Android</p></a
В описании товаров не должно быть тегов br, они допустимы для форматирования текста только в статичных секциях, каталог же является динамической, контент тут постоянно меняется

2021-01-25 13:21 UTC, JellyInLaw commented on catalog.html
> +        <form action="https://echo.htmlacademy.ru" method="get">
Получится что то вроде двух списков, в первом три элемента со ссылками внутри, во втором два?

2021-01-28 06:11 UTC, craz3r commented on catalog.html
> +        <form action="https://echo.htmlacademy.ru" method="get">
именно

2021-01-28 06:12 UTC, craz3r approved these changes

2021-01-28 06:12 UTC, merged